# alpine is commonly used to indicate that the 
# image has only the absolutely required libs and files
FROM node:alpine 

# sets the working directory inside the container
WORKDIR '/app'

# copy package.json and install dependencies 
COPY package.json .
RUN npm install

# copy the actual code, including tests
COPY . .

# start dev server
CMD ["npm", "run", "start"]